- name: Generate Serverkey
  ansible.builtin.shell: set -o pipefail && wg genkey | tee /etc/wireguard/private.key | wg pubkey > /etc/wireguard/public.key
  register: key_gen_result
  args:
    chdir: /etc/wireguard
    creates: /etc/wireguard/private.key

- name: Copy private key to variable
  ansible.builtin.command: cat /etc/wireguard/private.key
  register: private_key
  changed_when: false
