- name: Stop Wireguard
  ansible.builtin.service:
    name: wg-quick@{{ wg_interface_name }}
    state: stopped
    enabled: true

- name: Copy Wireguard Template
  ansible.builtin.template:
    src: wireguard/wg.conf.j2
    dest: /etc/wireguard/{{ wg_interface_name }}.conf
    owner: root
    group: root
    mode: 0600

- name: Start Wireguard
  ansible.builtin.service:
    name: wg-quick@{{ wg_interface_name }}
    state: started
    enabled: true
