# Work in Progress
- name: Install Wireguard
  hosts: wireguard
  tasks:
    - name: Install Packages
      ansible.builtin.import_tasks:
        file: wg_tasks/0_install_packages.yaml

    - name: Generate private Key
      ansible.builtin.import_tasks:
        file: wg_tasks/1_generate_private_key.yaml

    - name: Configure sysctl
      ansible.builtin.import_tasks:
        file: wg_tasks/2_configure_sysctl.yaml

    - name: Copy WG Config
      ansible.builtin.import_tasks:
        file: wg_tasks/3_copy_server_config.yaml

    - name: Add Peers
      ansible.builtin.import_tasks:
        file: wg_tasks/4_add_peer.yaml

    - name: Copy to local
      ansible.builtin.import_tasks:
        file: wg_tasks/5_create_client_qr.yaml
