# Work in Progress
- name: Install Wireguard
  hosts: test
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present

    - name: Generate Serverkey
      ansible.builtin.shell: set -o pipefail && wg genkey | tee /etc/wireguard/private.key | wg pubkey > /etc/wireguard/public.key
      register: serverkey
      args:
        chdir: /etc/wireguard
        creates: /etc/wireguard/private.key
