# Work in Progress
- name: Install Wireguard
  hosts: wireguard
  tasks:
    - name: Install Wireguard
      ansible.builtin.apt:
        name: wireguard
        state: present
        update_cache: true
      become: true
      become_method: sudo
      become_user: root

    - name: Generate Serverkey
      ansible.builtin.shell: |
        set -o pipefail
        wg genkey | tee /etc/wireguard/private.key | wg pubkey > /etc/wireguard/public.key
      register: serverkey
      args:
        chdir: /etc/wireguard
        creates: /etc/wireguard/private.key
      become: true
      become_method: sudo
      become_user: root
